# Generated by Django 4.2.7 on 2023-11-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Recipe Name', max_length=128, verbose_name='name')),
                ('description', models.TextField(blank=True, help_text='Recipe Description', null=True, verbose_name='description')),
            ],
        ),
    ]
